### ISSUE TITLE
printsolution doesn't work anymore with the new version of l3kernel

### ISSUE THREAD

**Issue by joneppie** [cgnieder/xsim#43]
If printsolution is used in the document, the following error is displayed with the current version of l3kernel:

`! LaTeX3 Error: File '' not found.`

If you continue compiling, the solution will be displayed correctly in the result document.

**Comment by u-fischer** [comment]
From https://tex.stackexchange.com/a/474897/2388:

This is due to a bug in \tl_set_from_file:Nnn, which has been deprecated and replaced by \file_get:nnN in expl3. A mistake in the order of arguments leads to the erroneous result. It will be fixed shortly, for the present try

~~~~
\ExplSyntaxOn
\cs_set_protected:Npn \tl_set_from_file:Nnn #1#2#3
  { \file_get:nnN {#3} {#2} #1 }
\ExplSyntaxOff
~~~~

**Comment by joneppie** [comment]
Will the bug in expl3 or xsim be fixed?

**Comment by u-fischer** [comment]
naturally. It is already fixed in the l3kernel sources, and will be uploaded today or tomorrow.
