### ISSUE TITLE
Poll: make “no-files” the default behavior?

### ISSUE THREAD

**Issue by cgnieder** [cgnieder/xsim#68]
I repeatedly get the complain that `xsim` creates so many files, often in combination with the use of collections. I have some ideas for a redesign of the collection mechanism which will a) make it more powerful and b) will avoid the multiple creation of the same exercise if it is put in more than one collection. But despite this (future) change I can't help but think that the behavior of the `no-files` option should be made default. Do you agree?

[![](https://api.gh-polls.com/poll/01E4VC96S7T96DR5ZN1CPAQPR7/yes)](https://api.gh-polls.com/poll/01E4VC96S7T96DR5ZN1CPAQPR7/yes/vote)
[![](https://api.gh-polls.com/poll/01E4VC96S7T96DR5ZN1CPAQPR7/no)](https://api.gh-polls.com/poll/01E4VC96S7T96DR5ZN1CPAQPR7/no/vote)

**Comment by pablgonz** [comment]
I think it would be a great idea, if it is accepted as a default change, I propose to place a warning message for the transition:

```
Package xsim Warning: The default loaded option is 'no-files'
```

**Comment by Piroooh** [comment]
I've just tested on my "big" and "small" files with multiple calls to the `xsim` collection. The results are leading me to be thought that `no-files` option should not be the default option.

1. The compiling time is such bigger with `no-files` option (from 1min50 to 3min56) ;
2. Compilation might be impossible because of exceeded tex capacity. Such very big project, with double compilation worked with `files` (about 1 hour compiling time) and doesn't compiled because of Tex capacity with `no-files` option.

For those results and for following reasons : 
- Existence of the `path/` xsim option who allowed us to keep a net directory ;
- Main problem (imo) with files is the multiple writing of the same exercise by calling our `input.tex` file multiple times and not that a file is created.

I suggest to keep the current default behaviour and `no-files` option as an option.

**Comment by cgnieder** [comment]
@Piroooh  but you have noticed that I plan to *completely* revise the collection mechanism? After that there won't be any unnecessary inputting of files. Any behavior related to collections should not influence the vote, please!

BTW: my current development version shows the opposite behavior: a small performance gain *with* the option active. These are the times for a file with 100 empty exercises:
```
without `no-files' option:
7.06 s 6.66 s first run
20.1 s 20.8 s consecutive runs

with `no-files' option:
4.83 s 5.01 s first run
20 s 20.2 s consecutive runs
```

**Comment by Piroooh** [comment]
It's difficult for me at the moment to answer to your poll with a tex distribution and behaviour of `xsim` that i can not test... Sure, if my results and reasons are no longer valid, i would prefer `no-files`. But for now, my answer concerns what i'm aware of.

**Comment by cgnieder** [comment]
> Btw : i'm very impatient to discover the new version with all teasing you made about this draft version !

I've just uploaded it (v0.19b) to CTAN. ;)

**Comment by cgnieder** [comment]
I will close this now on Jan. 1st 2021 with 23 votes yes and 16 votes no.
The upcoming version 0.20 will have `no-files=true` as default. A new load-time option `use-files` will be introduced.
